version: '3.8'

services:
  sofinco-bot:
    build: .
    container_name: sofinco-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Jakarta
